name: Update SuperBrave Rules

# Trigger workflow manually (via GitHub UI) or daily
on:
  workflow_dispatch:  # Manual trigger
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'info'
  schedule:           # Daily auto-run (UTC midnight)
    - cron: '0 0 * * *'

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full commit history

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'    # Cache pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main script
        run: python main.py

      - name: Check for changes
        id: changes
        run: |
          # Check if SuperBrave.txt was modified
          if git diff --quiet HEAD HEAD~1 -- SuperBrave.txt; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.no_changes == 'false'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add SuperBrave.txt
          git commit -m "chore(rules): Auto-update SuperBrave list - $(date +%Y-%m-%d)"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Authenticated push
